name: Check source codes

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd: ["lint"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - id: nvm
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.cmd }}
        run: pnpm ${{ matrix.cmd }}
